--- 
environment_tier: production
default_region: us-west-2
region: "{{ default_region.update(override_region) }}{{ default_region }}"
dns_points_to_load_balancer: "{{ load_balancers_enabled | bool }}"
