--- 
environment_tier: production
default_regions:
  - us-east-1
regions: "{{ default_regions.update(override_regions) }}{{ default_regions }}"
dns_points_to_load_balancer: "{{ load_balancers_enabled | bool }}"
