--- 
environment_tier: staging
default_regions:
  - us-west-2
regions: "{{ default_regions.update(override_regions) }}{{ default_regions }}"
dns_points_to_load_balancer: "{{ load_balancers_enabled | bool }}"
