---
- name: Create Database Subnet Group
  rds_subnet_group:
    state: present
    name: "{{ project }}-{{ system_role }}"
    description: "Database for {{ project }}"
    region: "{{ region }}"
    subnets: "{{ vpc.subnets | selectattr('resource_tags.Role', 'equalto', system_role) | map(attribute='id') | list }}"


- name: Create Database Servers
  rds:

    command: create

    region: "{{ region }}"
    multi_zone: yes

    instance_name: "{{ project }}-{{ system_role }}-{{ environment_tier }}"
    instance_type: "db.{{ instance_type[system_role] }}"

    vpc_security_groups: "{{ security_group_id[system_role] }}"
    subnet: "{{ project }}-{{ system_role }}"

    db_engine: "{{ rds_engine }}"
    upgrade: yes

    port: "{% if rds_engine == 'postgres' %}5432{%elif rds_engine == 'MySQL' %}3306{% endif %}"
    db_name: "{{ rds_database_name | mandatory }}"
    username: "{{ rds_database_username | mandatory }}"
    password: "{{ rds_database_password  | mandatory }}"

    backup_retention: "{{ rds_backup_retention }}"
    size: "{{ rds_database_size }}"
    wait: yes
    wait_timeout: 1500


- name: Create Database Servers | Read-Replica
  rds:

    command: replicate

    region: "{{ region }}"

    instance_name: "{{ project }}-{{ system_role }}-{{ environment_tier }}-replica"
    source_instance: "{{ project }}-{{ system_role }}-{{ environment_tier }}"

    wait: yes
    wait_timeout: 900
