---
- include_vars: "environment_tier/{{ environment_tier | mandatory }}.yml"
- include_vars: infrastructure/subnets.yml
- include_vars: infrastructure/security-groups.yml
- include_vars: infrastructure/load-balancers.yml
- include_vars: infrastructure/instances.yml
- include_vars: "region/{{ region | mandatory }}.yml"
